@php
    $period = $report['period'];
    $product = $report['product'] ?? null;
    $summary = $report['detail_summary'] ?? null;
    $number = fn (int|float|string|null $value): string => number_format((float) ($value ?? 0), 4, ',', '.');
    $logoPath = public_path('images/yokprinting-logo.png');
    $logo = file_exists($logoPath) ? 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath)) : null;
    $typeLabel = fn (string $type): string => match ($type) {
        'opening_balance' => 'Saldo awal', 'purchase' => 'Pembelian / penerimaan', 'sale' => 'Penjualan',
        'adjustment' => 'Penyesuaian', 'stock_opname' => 'Stok opname', 'return' => 'Retur barang',
        default => 'Mutasi stok',
    };
@endphp
<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><title>Mutasi per Barang</title><style>
@page{margin:28px 30px}*{box-sizing:border-box}body{color:#0f172a;font-family:"DejaVu Sans",Arial,sans-serif;font-size:8px;line-height:1.35;margin:0}.header{border-bottom:2px solid #2563eb;display:table;margin-bottom:14px;padding-bottom:10px;width:100%}.header-cell{display:table-cell;vertical-align:middle}.header-right{text-align:right;width:55%}.logo{width:130px}h1{font-size:18px;margin:0 0 4px}.muted{color:#64748b}.period{color:#1d4ed8;font-size:9px;font-weight:700}.summary{display:table;margin-bottom:14px;width:100%}.summary-cell{border:1px solid #dbe2ea;display:table-cell;padding:8px;width:25%}.summary-cell+.summary-cell{border-left:0}.label{color:#64748b;font-size:7px;font-weight:700;text-transform:uppercase}.value{font-size:13px;font-weight:700;margin-top:3px}.green{color:#047857}.red{color:#be123c}.blue{color:#1e3a8a}table{border-collapse:collapse;width:100%}th{background:#dbeafe;border:1px solid #cbd5e1;color:#1e3a8a;font-size:7px;padding:6px;text-align:left}td{border:1px solid #e2e8f0;padding:6px;vertical-align:top}td.amount,th.amount{text-align:right;white-space:nowrap}.opening td{background:#f8fafc}.note{background:#f8fafc;border:1px solid #e2e8f0;color:#475569;margin-top:10px;padding:7px 9px}.footer{border-top:1px solid #e2e8f0;color:#64748b;font-size:7px;margin-top:12px;padding-top:6px;text-align:center}
</style></head><body>
<div class="header"><div class="header-cell">@if ($logo)<img class="logo" src="{{ $logo }}" alt="YokPrinting.ID">@else<strong>YokPrinting.ID</strong>@endif</div><div class="header-cell header-right"><h1>Mutasi per Barang</h1><div class="period">PERIODE {{ $period['start_date'] }} s.d. {{ $period['end_date'] }}</div>@if ($product)<div class="muted">{{ $product['sku'] }} · {{ $product['name'] }}</div>@else<div class="muted">Ringkasan seluruh produk</div>@endif</div></div>
@if ($product && $summary)
<div class="summary"><div class="summary-cell"><div class="label">Saldo awal</div><div class="value">{{ $number($summary['opening_balance']) }}</div></div><div class="summary-cell"><div class="label">Barang masuk</div><div class="value green">{{ $number($summary['incoming']) }}</div></div><div class="summary-cell"><div class="label">Barang keluar</div><div class="value red">{{ $number($summary['outgoing']) }}</div></div><div class="summary-cell"><div class="label">Saldo akhir</div><div class="value blue">{{ $number($summary['closing_balance']) }}</div></div></div>
<table><thead><tr><th>Nomor dokumen</th><th>Tanggal</th><th>Tipe mutasi</th><th>Deskripsi / keterangan</th><th>Customer / Supplier</th><th class="amount">Masuk</th><th class="amount">Keluar</th><th class="amount">Saldo</th></tr></thead><tbody>@foreach ($report['mutations'] ?? [] as $row)<tr class="{{ ($row['type'] ?? '') === 'opening_balance' ? 'opening' : '' }}"><td>{{ $row['document_number'] ?: '-' }}</td><td>{{ $row['date'] ?: '-' }}</td><td>{{ $typeLabel((string) ($row['type'] ?? '')) }}</td><td>{{ $row['description'] ?: '-' }}</td><td>{{ $row['party'] ?: '-' }}</td><td class="amount">{{ $row['incoming'] ? $number($row['incoming']) : '-' }}</td><td class="amount">{{ $row['outgoing'] ? $number($row['outgoing']) : '-' }}</td><td class="amount">{{ $number($row['balance']) }}</td></tr>@endforeach</tbody></table>
<div class="note">Status rekonsiliasi: <strong>{{ $summary['reconciliation_status'] ?? 'not_applicable' }}</strong>. Saldo ledger {{ $number($summary['ledger_stock'] ?? 0) }}, stok produk {{ $number($summary['product_stock'] ?? 0) }}, selisih {{ $number($summary['difference'] ?? 0) }}.</div>
@else
<table><thead><tr><th>SKU</th><th>Nama produk</th><th>Kategori</th><th>Unit</th><th class="amount">Saldo awal</th><th class="amount">Masuk</th><th class="amount">Keluar</th><th class="amount">Penyesuaian</th><th class="amount">Saldo akhir</th><th class="amount">Nilai FIFO</th></tr></thead><tbody>@foreach ($report['products'] ?? [] as $row)<tr><td>{{ $row['sku'] }}</td><td>{{ $row['name'] }}</td><td>{{ $row['category'] ?: '-' }}</td><td>{{ $row['unit'] }}</td><td class="amount">{{ $number($row['opening_balance']) }}</td><td class="amount">{{ $number($row['incoming_quantity']) }}</td><td class="amount">{{ $number($row['outgoing_quantity']) }}</td><td class="amount">{{ $number($row['adjustments']) }}</td><td class="amount">{{ $number($row['closing_balance']) }}</td><td class="amount">{{ $number($row['fifo_inventory_value']) }}</td></tr>@endforeach</tbody></table>
@endif
<div class="footer">Dibuat oleh YokPrinting.ID pada {{ now(config('app.timezone'))->translatedFormat('d M Y H:i') }}</div></body></html>
